import {assert} from '../lib/util.mjs';
export const cases=[
{id:'REG-001',domain:'REG',name:'computed.peek() must be fresh',async run({a}){const s=a.signal(1),c=a.computed(()=>s.get()*2);assert(c.get()===2);s.set(3);assert(c.peek()===6)}},
{id:'REG-002',domain:'REG',name:'batch exception must not leave queue corrupted',async run({a}){const s=a.signal(0);try{a.batch(()=>{s.set(1);throw new Error('x')})}catch{}a.batch(()=>s.set(2));assert(s.get()===2)}},
{id:'REG-003',domain:'REG',name:'boot failure must permit valid retry',async run({a}){const c=a.createCore();let n=0;c.modules.register({name:'m',init:async()=>{if(n++===0)throw new Error('x')},teardown:async()=>{}});try{await c.boot()}catch{}await c.boot();assert(c.phase===a.LifecyclePhase.READY);await c.destroy()}},
{id:'REG-004',domain:'REG',name:'service definitions survive rollback',async run({a}){const c=a.createCore();c.services.provide('x',()=>({v:1}));c.modules.register({name:'bad',init:async()=>{throw new Error('x')}});try{await c.boot()}catch{}assert(c.services.has('x'),'service definition lost during rollback')}},
{id:'REG-005',domain:'REG',name:'direct unresolved service gets final cleanup',async run({a}){const c=a.createCore();let d=0;c.services.provide('direct',{onDestroy(){d++}});await c.destroy();assert(d===1)}},
{id:'REG-006',domain:'REG',name:'default Core services remain available after recovery',async run({a}){const c=a.createCore();let once=true;c.modules.register({name:'m',init:async()=>{if(once){once=false;throw new Error('x')}},teardown:async()=>{}});try{await c.boot()}catch{}for(const k of ['events','storage','navigation','diagnostics','timeTravel'])assert(c.services.has(k),`missing ${k}`)}},
{id:'REG-007',domain:'REG',name:'second navigation works',async run({a}){const c=a.createCore();c.router.add('/a',{render:()=>1});c.router.add('/b',{render:()=>2});await c.boot();await c.navigate('/a');const r=await c.navigate('/b');assert(r.pathname==='/b');await c.destroy()}},
{id:'REG-008',domain:'REG',name:'redirect works',async run({a}){const c=a.createCore();c.router.add('/a',{render:()=>1});c.router.add('/b',{render:()=>2});c.navigation.beforeEach(ctx=>ctx.route.pathname==='/a'?{redirect:'/b'}:true);await c.boot();const r=await c.navigate('/a');assert(r.pathname==='/b');await c.destroy()}},
{id:'REG-009',domain:'REG',name:'existing storage survives failed boot',async run({a}){const s=new a.MemoryStorageAdapter('cvrsREG','storage');await s.clear();await s.set('k',7);const c=a.createCore({storageAdapter:s});c.modules.register({name:'bad',init:async()=>{throw new Error('x')}});try{await c.boot()}catch{}assert(await s.get('k')===7)}},
{id:'REG-010',domain:'REG',name:'PageRegistry/Router compatibility',async run({a}){const c=a.createCore();c.pages.register({id:'p',route:'/p',render:()=>1});const m=c.router.match('/p');assert(m.matched&&m.metadata.pageId==='p')}}
];
